config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  authenticate :admin do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :users
  authenticate :user do
    resources :users
    resources :publications do
      resource :build, controller: 'publications/build'
      put :pause
    end
  end
  HighVoltage.configure do |config|
    config.route_drawer = HighVoltage::RouteDrawers::Root
  end

  mount API => '/api/'

  get "/translate", to: redirect("http://stark-cliffs-2158.herokuapp.com/projects/1")
end

app/models/publication.rb
class Publication < ActiveRecord::Base
  belongs_to :property, inverse_of: :publications
  belongs_to :user, inverse_of: :publications
  belongs_to :publication_type, inverse_of: :publications
  has_one :location, through: :property

  OPERATION_TYPES = ["Venta", "Alquiler", "Alquiler temporal", "Tiempo Compartido"]
  CURRENCY = ["$", "u$s"]

  scope :wizard_finished, -> { where(status: 'active') }
  scope :actives, -> { where(status: 'active').where("end_date > ?",Time.zone.now) }
  scope :sort_by_priority, -> { joins(:publication_type).order("publication_types.priority_on_search DESC") }

  accepts_nested_attributes_for :property, update_only: true

  validates :user, presence: true
  validates :operation_type, presence: true, if: :active_or_operation_type?
  validates :operation_type, inclusion: {in: OPERATION_TYPES}, if: :active_or_operation_type?
  validates :publication_type, presence: true, if: :active_or_publication_type?
  validates :property, presence: true, if: :active_or_property_type?
  validates_associated :property, if: :active_or_property_type?
  validates :price, :currency, presence: true, if: :active_or_data_input_three?

  before_update :initialize_dates

  def state
    if Time.zone.now > end_date
      "finished"
    elsif active
      "active"
    else
      "paused"
    end
  end

  def price_with_currency
    "#{currency}#{price}"
  end

  def highlight
    publication_type.highlight
  end

  def wizard_finished?
    status == 'active'
  end

  def active_or_operation_type?
    status.include?('operation_type')
  end

  def active_or_publication_type?
    status.include?('publication_type')
  end

  def active_or_property_type?
    status.include?('property_type')
  end

  def active_or_data_input_one?
    status.include?('data_input_one')
  end

  def active_or_data_input_two?
    status.include?('data_input_two')
  end

  def active_or_data_input_three?
    status.include?('data_input_three')
  end

  def active_or_payment?
    status.include?('payment')
  end

  def pause
    self.active = !active
    save
  end

  private #==========================================================

  def initialize_dates
    if wizard_finished?
      self.start_date = Time.zone.now
      self.end_date = start_date + publication_type.publication_days.days
    end
  end
end

app/models/publication_type.rb
class PublicationType < ActiveRecord::Base
  has_many :publications
end

app/controllers/publications/build_controller.rb
class Publications::BuildController < ApplicationController
  include Wicked::Wizard

  steps :operation_type, :publication_type, :property_type,
       :data_input_two, :data_input_three, :data_input_one, :payment

  before_action :set_publication, only: [:show, :update]

  def show
    generate_default_publication
    render_wizard
  end

  def update
    params[:publication]||={}
    params[:publication][:status] = step.to_s
    params[:publication][:status] = 'active' if step == steps.last
    @publication.update_attributes(publication_params)
    if @publication.valid?
      render_wizard @publication
    else
      generate_default_publication
      render_wizard
    end
  end

  def create
    @publication = Publication.create user: current_user
    redirect_to wizard_path(steps.first, :publication_id => @publication.id)
  end

  private #==================================================

  def finish_wizard_path
    publications_path
  end

  def publication_params
    params.require(:publication).
        permit(:operation_type, :property_id, :publication_type_id, :currency,
               :price, :status, property_attributes:
            [
                :id, :property_type_id, :address, :location_id, :description,
                images_attributes:
                    [
                        :id, :file
                    ],
                videos_attributes:
                    [
                        :id, :url
                    ],
                characteristic_instances_attributes:
                    [
                        :characteristic_id, :type, :string,
                        :integer, :boolean, :values, :id
                    ]
            ]
    )
  end

  def generate_default_publication
    if step == :data_input_one
      (@publication.property.images.count .. @publication.publication_type.images_count-1).each do
        @publication.property.images.build
      end
      (@publication.property.videos.count .. @publication.publication_type.videos_count-1).each do
        @publication.property.videos.build
      end
    end

    if step == :data_input_two
      @publication.property.property_type.characteristics.each do |characteristic|
        CharacteristicInstance.find_or_create_by( characteristic: characteristic, property: @publication.property) do |instance|
          instance.type = "CharacteristicInstance::#{characteristic.characteristic_type}"
        end
      end
    end

  end

  def set_publication
    @publication = Publication.find(params[:publication_id])
    @publication.build_property(user: current_user) unless @publication.property
    @first = (step == steps.first)
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

       # GET /publications
  # GET /publications.json
  def index
    @search = Publication.wizard_finished.search(params[:q])
    @publications = @search.result
    @search.build_sort if @search.sorts.empty?
    @publications = @publications.page params[:page]
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.user= current_user

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PUT /publications/1/pause
  def pause
    @publication = Publication.find(params[:publication_id])
    @publication.pause
    redirect_to publications_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
      @publication.user= current_user
    end
end

app/helpers/publications/build_helper.rb
module Publications::BuildHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
  def state_tag state
    "<span class='label label-#{state_class state}'> #{t("activerecord.attributes.publication.status.#{state}")} </span>".html_safe
  end

  def state_class state
    case state
      when "finished"
        "danger"
      when "active"
        "success"
      when "paused"
        "default"
    end
  end

  def check_icon_tag value
    if value
      '<span class="main-color icon_check_alt2"></span>'.html_safe
    else
      '<span class="main-color icon_close_alt2" style="color: #ac2925"></span>'.html_safe
    end
  end

  def status_button_tag state
    case state
      when "finished"
        '<span class="glyphicon glyphicon-repeat"></span>'.html_safe
      when "active"
        '<span class="glyphicon glyphicon-pause"></span>'.html_safe
      when "paused"
        '<span class="glyphicon glyphicon-play"></span>'.html_safe
    end
  end
end

app/views/publications/_form.html.erb
<%= form_for @publication, :html => { :class => "form-horizontal publication" } do |f| %>

    <% if @publication.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@publication.errors.count, "error") %> prohibited this publication from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @publication.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

    <div class="form-group">
      <%= f.label :operation_type, :class => 'col-md-4 control-label' %>
      <div class="col-md-4">
        <%= f.select :operation_type, Publication::OPERATION_TYPES, {prompt: "Seleccione..."}, :class => 'form-control' %>
      </div>
      <%= error_span(@publication[:operation_type]) %>
    </div>
    <div class="form-group">
      <%= f.label :publication_type_id, :class => 'col-md-4 control-label' %>
      <div class="col-md-4">
        <%= f.select :publication_type_id, PublicationType.all.map{|t|[t.name, t.id]}, {prompt: "Seleccione..."}, :class => 'form-control' %>
      </div>
      <%= error_span(@publication[:publication_type_id]) %>
    </div>
    <div class="form-group">
      <%= f.label :property_id, :class => 'col-md-4 control-label' %>
      <div class="col-md-4">
        <%= f.select :property_id, Property.all.map{|t|[t.id, t.id]}, {prompt: "Seleccione..."}, :class => 'form-control' %>
      </div>
      <%= error_span(@publication[:property_id]) %>
    </div>
    <div class="form-group">
      <%= f.label :price, :class => 'col-md-4 control-label' %>
      <div class="col-md-4">
        <%= f.number_field :price, :class => 'form-control' %>
      </div>
      <%= error_span(@publication[:property_id]) %>
    </div>
    <div class="form-group">
      <%= f.label :currency, :class => 'col-md-4 control-label' %>
      <div class="col-md-4">
        <%= f.select :currency, Publication::CURRENCY.map{|c|[c,c]}, {prompt: "Seleccione..."}, :class => 'form-control' %>
      </div>
      <%= error_span(@publication[:property_id]) %>
    </div>

  <br/>
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            publications_path, :class => 'btn btn-default' %>

<% end %>

app/views/publications/edit.html.erb
<%- model_class = Publication -%>
<div class="panel-heading">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<div class="panel-body">
<%= render :partial => 'form' %>
</div>

app/views/publications/index.html.erb
<%- model_class = Publication -%>
<div class="panel-heading">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<div class="panel-body">
<%= search_form_for @search, :html => { :class => "form-horizontal" } do |f| %>

   <fieldset>

      <div class="form-group">
        <%= f.label :price_gteq, t("publication.search.price_from"), :class => 'col-md-2 control-label' %>
        <div class="col-md-4">
        <%= f.text_field :price_gteq, :class => 'form-control' %>
        </div>
        <%= f.label :price_lteq, t("publication.search.price_to"), :class => 'col-md-2 control-label' %>
        <div class="col-md-4">
        <%= f.text_field :price_lteq, :class => 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :property_address_cont, t("publication.search.address"), :class => 'col-md-2 control-label', for: 'q_property_address_cont' %>
        <div class="col-md-4">
        <%= f.text_field :property_address_cont, :class => 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-4">
          <%= f.submit t("publication.search.button"), :class => 'btn btn-default' %>
        </div>
      </div>
   </fieldset>
<% end %>
  <br/>
<table class=" table table-striped">
  <thead>
    <tr>
      <th><%= sort_link @search, :operation_type, model_class.human_attribute_name(:operation_type) %></th>
      <th><%= sort_link @search, :property_address, model_class.human_attribute_name(:address) %></th>
      <th><%= sort_link @search, :active, model_class.human_attribute_name(:state) %></th>
      <th><%= sort_link @search, :price, model_class.human_attribute_name(:price) %></th>
      <th><%= sort_link @search, :end_date, model_class.human_attribute_name(:end_date) %></th>
      <th><%= sort_link @search, :publication_type, model_class.human_attribute_name(:publication_type) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @publications.each do |publication| %>
      <tr>
        <td><%= publication.operation_type %></td>
        <td><%= publication.property.try(:address) %></td>
        <td><%= state_tag publication.state %></td>
        <td><%= publication.price_with_currency %></td>
        <td><%= publication.end_date %></td>
        <td><%= publication.publication_type.name %></td>
        <td>
          <%= link_to publication_pause_path(publication),
                      :method => :put, :class => 'btn btn-default btn-xs' do %>
              <%= status_button_tag publication.state %>
          <% end %>
          <%= link_to publication_path(publication), :class => 'btn btn-info btn-xs' do %>
              <i class="fa fa-info"></i>
          <% end %>
          <%= link_to publication_path(publication),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Estas seguro?')) },
                      :class => 'btn btn-xs btn-danger' do %>
              <i class="fa fa-trash-o fa-lg"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
  <%= paginate @publications %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            publication_build_path(publication_id: 'new'),
            method: :post,
            :class => 'btn btn-primary' %>
</div>

app/views/publications/new.html.erb
<%- model_class = Publication -%>
<div class="panel-heading">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<div class="panel-body">
<%= render :partial => 'form' %>
</div>

app/views/publications/show.html.erb
<%- model_class = Publication -%>
<div class="panel-heading">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="panel-body">
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:operation_type) %>:</strong></dt>
  <dd><%= @publication.operation_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:publication_type) %>:</strong></dt>
  <dd><%= @publication.publication_type.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:property_type) %>:</strong></dt>
  <dd><%= @publication.property.property_type.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @publication.price_with_currency %></dd>
  <dt><strong><%= Property.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @publication.property.address %></dd>
  <dt><strong><%= Property.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @publication.property.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= t @publication.state %></dd>
  <dt><strong><%= Property.human_attribute_name(:location_id) %>:</strong></dt>
  <dd><%= @publication.property.location.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_date) %>:</strong></dt>
  <dd><%= @publication.start_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_date) %>:</strong></dt>
  <dd><%= @publication.end_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:images) %>:</strong></dt>
  <dd>
  <% @publication.property.images.each do |image| %>
    <%= image_tag image.file.url, class: 'img-thumbnail', style: 'max-width: 140px; max-height: 140px;' %>
  <% end %>
  </dd>
  <dt><strong><%= model_class.human_attribute_name(:videos) %>:</strong></dt>
  <% @publication.property.videos.each do |video| %>
    <dd><%= link_to video.url, video.url %></dd>
  <% end %>
  <% @publication.property.characteristic_instances.each do |instance| %>
    <dt><strong><%= instance.characteristic.name %>:</strong></dt>
      <dd>
      <% case instance.type %>
      <% when "CharacteristicInstance::Boolean" %>
          <%= instance.boolean %>
      <% when "CharacteristicInstance::Integer" %>
          <%= instance.integer %>
      <% when "CharacteristicInstance::String" %>
          <%= instance.string %>
      <% when "CharacteristicInstance::Values" %>
          <%= instance.values %>
      <% end%>
      </dd>
  <% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              publications_path, :class => 'btn btn-default'  %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              publication_path(@publication),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Estas seguro?')) },
              :class => 'btn btn-danger' %>
</div>