config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  authenticate :admin do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :users
  authenticate :user do
    resources :users
    resources :publications do
      resource :build, controller: 'publications/build'
      put :pause
    end
  end
  HighVoltage.configure do |config|
    config.route_drawer = HighVoltage::RouteDrawers::Root
  end

  mount API => '/api/'

  get "/translate", to: redirect("http://stark-cliffs-2158.herokuapp.com/projects/1")
end

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<div class="navbar navbar-default navbar-static-top animated fadeInDown header-shadow">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/publications"><%= image_tag "logo-black.png" , style: "width: 50px;"%></a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/right_navigation_links' %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_right_navigation_links.html.erb
<% if user_signed_in? %>
    <li class="<%= "active" if params[:controller] == "devise/registrations" %>"><%= link_to t("app.navigation.account"), edit_user_registration_path %></li>
    <li><%= link_to t("app.navigation.logout"), destroy_user_session_path, :method=>'delete' %></li>
<% end %>

app/views/layouts/_side_bar.html.erb
<div class="panel sidebar-nav animated bounceInDown container-shadow">
  <div class="panel-heading">
    <h4><%= t "app.sidebar.title" %></h4>
  </div>
  <div class="panel-body">
      <ul class="list-group">
        <%= render 'layouts/side_bar_links' %>
      </ul>
  </div>
</div><!--/.well -->

app/views/layouts/_side_bar_links.html.erb
<%= link_to "Publicaciones", publications_path, class: "list-group-item #{params[:controller] == "publications" ? "active" : ""}"  %>
<%= link_to "Transacciones", "/path3", class: "list-group-item #{params[:controller] == "transactions" ? "active" : ""}"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) :t("app.title") %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="wrap">
      <%= render 'layouts/navigation' %>
      <div class="container">
        <div class="row">
          <div class="col-md-12 flash-container">
            <%= bootstrap_flash class: "container-shadow animated bounceInLeft" %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-3">
            <%= render 'layouts/side_bar' %>
          </div><!--/span-->
          <div class="col-md-9">
            <div class="panel main-container <%= unless controller_name == 'registrations'; "animated flipInY container-shadow" end %>">
              <%= yield %>
            </div>
          </div>
        </div>
      </div> <!-- /container -->
    </div>
    <div class="footer">
      <div class="container">
        <p><%= t("app.footer").html_safe %></p>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : t("app.title") %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : t("app.title") %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
       <%= yield %>
  </body>
</html>

app/views/layouts/static.html.erb
<%= yield %>